[workspace]
resolver = "3"
members = [
    "lsf",
    "cardinal-sdk",
    "fswalk",
    "namepool",
    "pathbytes",
    "was",
    "lsf-tui",
    "query-segmentation",
]
exclude = [
    "cardinal",
]
